CREATE TABLE Student 
(
    STUDENT_ID CHAR(10) CONSTRAINT pk_student PRIMARY KEY,
    FIRST_NAME VARCHAR2(20) CONSTRAINT nn_first_name NOT NULL,
    LAST_NAME VARCHAR2(20) CONSTRAINT nn_last_name NOT NULL,
    CNIC CHAR(13) CONSTRAINT uq_cnic UNIQUE,
    GENDER CHAR(1) CONSTRAINT ck_gender CHECK (GENDER IN ('M', 'F')),
    DOB DATE,
    ADDRESS VARCHAR2(50),
    PHONE CHAR(13) CONSTRAINT nn_phone NOT NULL,
    DEPTNO NUMBER CONSTRAINT fk_deptno REFERENCES Department(DEPTNO)
);


CREATE TABLE Graduate_Student 
(
    STUDENT_ID CHAR(10) CONSTRAINT pk_graduate_student PRIMARY KEY REFERENCES Student(STUDENT_ID),
    THESIS_ADVISOR CHAR(10) CONSTRAINT fk_thesis_advisor REFERENCES Instructor(INSTRUCTOR_ID),
    THESIS_STATUS VARCHAR2(20) CONSTRAINT ck_thesis_status CHECK (THESIS_STATUS IN ('COMPLETE', 'IN PROGRESS'))
);


CREATE TABLE Undergraduate_Student 
(
    STUDENT_ID CHAR(10) CONSTRAINT pk_undergraduate_student PRIMARY KEY REFERENCES Student(STUDENT_ID),
    FYP_ADVISOR CHAR
    (10) CONSTRAINT fk_fyp_advisor REFERENCES Instructor(INSTRUCTOR_ID)
);


CREATE TABLE Department 
(
    DEPTNO NUMBER CONSTRAINT pk_department PRIMARY KEY,
    DEPTNAME VARCHAR2(50) CONSTRAINT nn_deptname NOT NULL,
    HOD CHAR(10) CONSTRAINT fk_hod REFERENCES Instructor(INSTRUCTOR_ID)
);


CREATE TABLE Instructor 
(
    INSTRUCTOR_ID CHAR(10) CONSTRAINT pk_instructor PRIMARY KEY,
    FIRST_NAME VARCHAR2(20) CONSTRAINT nn_instructor_first_name NOT NULL,
    LAST_NAME VARCHAR2(20) CONSTRAINT nn_instructor_last_name NOT NULL,
    EMAIL VARCHAR2(30) CONSTRAINT uq_instructor_email UNIQUE,
    PHONE CHAR(13) CONSTRAINT nn_instructor_phone NOT NULL
);

CREATE TABLE Room 
(
    ROOMNO NUMBER CONSTRAINT pk_room PRIMARY KEY,
    CAPACITY NUMBER CONSTRAINT ck_capacity CHECK (CAPACITY > 0)
);


CREATE TABLE Course 
(
    COURSE_CODE VARCHAR2(10) CONSTRAINT pk_course PRIMARY KEY,
    COURSE_TITLE VARCHAR2(50) CONSTRAINT nn_course_title NOT NULL,
    CREDIT_HOURS NUMBER CONSTRAINT ck_credit_hours CHECK (CREDIT_HOURS BETWEEN 0.5 AND 3)
);


Pre_Requisite_Course
CREATE TABLE Pre_Requisite_Course 
(
    COURSE_CODE VARCHAR2(10) CONSTRAINT fk_course_code REFERENCES Course (COURSE_CODE),
    PRE_REQ VARCHAR2(10) CONSTRAINT fk_pre_req REFERENCES Course (COURSE_CODE),
    CONSTRAINT pk_pre_requisite_course PRIMARY KEY (COURSE_CODE, PRE_REQ)
);



Class
CREATE TABLE Class 
(
    INSTRUCTOR_ID CHAR (10) CONSTRAINT fk_class_instructor REFERENCES Instructor (INSTRUCTOR_ID),
    COURSE_CODE VARCHAR2(10) CONSTRAINT fk_class_course REFERENCES Course (COURSE_CODE),
    ROOM_NO NUMBER CONSTRAINT fk_class_room REFERENCES Room(ROOMNO),
    CONSTRAINT pk_class PRIMARY KEY (INSTRUCTOR_ID, COURSE_CODE)
);


CREATE TABLE Enrollment 
(
    STUDENT_ID CHAR(10) CONSTRAINT fk_enrollment_student REFERENCES Student(STUDENT_ID),
    COURSE_CODE VARCHAR2(10) CONSTRAINT fk_enrollment_course REFERENCES Course(COURSE_CODE),
    ENROLLMENT_DATE DATE,
    GRADE CHAR(1) CONSTRAINT ck_grade CHECK (GRADE IN ('A', 'B', 'C', 'D', 'F')),
    STATUS CHAR(4) CONSTRAINT ck_status CHECK (STATUS IN ('PASS', 'FAIL')),
    CONSTRAINT pk_enrollment PRIMARY KEY (STUDENT_ID, COURSE_CODE)
);


